on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: helloworldrcontainer.azurecr.io
        username: ${{ secrets.acr_helloworldrcontainer_username }}
        password: ${{ secrets.acr_helloworldrcontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Helloworld" -f  "Helloworld/Dockerfile" -t helloworldrcontainer.azurecr.io/helloworldaks:${{ github.sha }} --label dockerfile-path=Helloworld/Dockerfile
        docker push helloworldrcontainer.azurecr.io/helloworldaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_helloworldaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep helloworldaks849f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace helloworldaks849f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: helloworldaks849f
        container-registry-url: helloworldrcontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_helloworldrcontainer_username }}
        container-registry-password: ${{ secrets.acr_helloworldrcontainer_password }}
        secret-name: helloworldakdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: helloworldaks849f
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          helloworldrcontainer.azurecr.io/helloworldaks:${{ github.sha }}
        imagepullsecrets: |
          helloworldakdockerauth
